version: "3"
services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment: 
      NODE_ENV: "production"
    ports:
      - "80:80"
  backend:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    