version: "3"
services:
  backend:
    volumes:
      - ./api:/usr/src/app
      - ./rlm:/usr/src/rlm

  frontend:
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      VUE_APP_BACKEND_URL: http://localhost:5000
    volumes:
      - ./web:/app
    ports:
      - "80:8080"