version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment: 
      NODE_ENV: "production"
    ports:
      - "80:80"
    depends_on: 
      - backend
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    environment: 
      PORT: "5000"
    env_file: ./api/.env
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - dbserver
  dbserver:
    container_name: dbserver
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
    