version: "3"
services:
  # Vue.js frontend SPA
  frontend:
    container_name: frontend
    build:
      # Build the production container by default
      # using NGINX to proxy the HTTP requests
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      # Set the Node.js environment variable
      NODE_ENV: "production"
    ports:
      # Pull the web port mapping from the shell environment
      # with a default mapping of 80 --> 80.
      # During production, this should be "80:80" - so leave default
      # During development, this should be "80:8080" - specify when launching
      # Example: WEB_PORT=80:8080 docker-compose ...
      - ${WEB_PORT:-80:80}
    depends_on: 
      - backend
    restart: "unless-stopped"

  # Node.js backend REST API
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: "production"
      PORT: "5000"
    env_file: ./api/.env
    ports:
      - "5000:5000"
    volumes:
      # Give control of host machine's Docker engine
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - dbserver
    restart: "unless-stopped"

  # Dockerized MongoDB server
  dbserver:
    container_name: dbserver
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: "unless-stopped"

volumes:
  db_data:
    