# Pull the base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Install the Vue CLI service
RUN npm install -g @vue/cli

# Copy the package files
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the application files
COPY . .

# Expose the application port
# EXPOSE 8080

# Run the server
CMD ["npm", "run", "serve"]