# Pull the base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy the package files
COPY package*.json ./

# Install the project dependencies
RUN npm install

# Copy the application files
COPY ./src .

# Run the server
CMD ["npm", "run", "serve"]