###############
# BUILD STAGE #
###############

# Pull a lightweight alpine image to build the Vue.js application
FROM node:lts-alpine as build

# Set the working directory
WORKDIR /app

# Copy the package files
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the production app
RUN npm run build

####################
# PRODUCTION STAGE #
####################

# Pull the Nginx image
FROM nginx:alpine as prod

# Copy the production Vue.js files
COPY --from=build /app/dist /usr/share/nginx/app

# Add in the Nginx configuration
ADD ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose the main web port
EXPOSE 80